for number in range(1, 10, 2):
    print("attempt", number, number * ".")
# This code prints the word "attempt" followed by the current number and a series of dots.
# The range function generates numbers from 1 to 9, stepping by 2 each time.
# The output will be:
# attempt 1 .
# attempt 3 ...
# attempt 5 .....
# attempt 7 .......
# attempt 9 .......
# The loop iterates through the odd numbers in that range.
